/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import code.product;
import code.readcsv;
import data.loadData;
import java.awt.print.PrinterException;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author Praveen
 */
public class customer_behavior_product extends javax.swing.JFrame {

    /**
     * Creates new form BestSelling_Products
     */
    public customer_behavior_product() {
        initComponents();
        show_product_data();
    }
private List<readcsv> loadedData;

    private void load_CSV() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            loadedData = loadData.loadcsv(selectedFile);
            display_product_data_table(loadedData);
//            ;
        }
    }

    private void display_product_data_table(List<readcsv> dataList) {
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dataList.size(); i++) {
            readcsv row = dataList.get(i);
            model.addRow(new Object[]{
                row.getTra_id(),
                row.getC_id(),
                row.getP_id(),
                row.getP_name(),
                row.getQuantity(),
                row.getP_unit(),
                row.getDate(),
                row.getPrice(),
                row.getRegion()

            });
        }
    }
    //retriew Code

    public ArrayList<product> ProductList() {
        ArrayList<product> ProductList = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {

                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ProductList;
    }

    public void show_product_data() {
        ArrayList<product> list = ProductList();
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        Object[] row = new Object[9];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTra_id();
            row[1] = list.get(i).getC_id();
            row[2] = list.get(i).getP_id();
            row[3] = list.get(i).getP_name();
            row[4] = list.get(i).getQuantity();
            row[5] = list.get(i).getP_unit();
            row[6] = list.get(i).getDate();
            row[7] = list.get(i).getPrice();
            row[8] = list.get(i).getRegion();

            model.addRow(row);
        }

    }

    private void print_data() {
        try {
            boolean complete = tbl_product.print(JTable.PrintMode.FIT_WIDTH,
                    new MessageFormat("Datas"),
                    new MessageFormat("Page {0}"));
            if (complete) {
                JOptionPane.showMessageDialog(null, "Complete");
            } else {
                JOptionPane.showMessageDialog(null, "Not Complete");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        btn_bar_chart = new javax.swing.JButton();
        btn_line_chart1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btn_log_Out1 = new javax.swing.JButton();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        jCheckBox1.setText("jCheckBox1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Sampath Food City (PVT) Ltd ");

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " TransactionID", "CustomerID", "ProductID", "ProductName", "Quantity	", "PriceperUnit", "Date", "TotalPrice", "Region"
            }
        ));
        jScrollPane1.setViewportView(tbl_product);

        btn_bar_chart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_bar_chart.setText("Pie Chart");
        btn_bar_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bar_chartActionPerformed(evt);
            }
        });

        btn_line_chart1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_line_chart1.setText("Print");
        btn_line_chart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_line_chart1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Customer behavior Analysis ");

        btn_log_Out1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_log_Out1.setText("Home");
        btn_log_Out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_Out1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_line_chart1)
                        .addGap(20, 20, 20)
                        .addComponent(btn_bar_chart))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btn_log_Out1)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)))
                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(16, 16, 16)
                .addComponent(btn_log_Out1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_line_chart1)
                    .addComponent(btn_bar_chart))
                .addContainerGap(164, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_bar_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bar_chartActionPerformed
                                           
    DefaultPieDataset dataset = new DefaultPieDataset();

        try {
            Connection con = database.db.getConnection();
            Statement st = con.createStatement();

            // Example: fetching total sales per product (like customer behavior)
            String[] products = {"Fish", "Beef", "Chicken", "Yogurt", "Cereal", "Cheese", "Bread", "Banana", "Milk", "Apple"};

            for (String product : products) {
                String query = "SELECT SUM(price) AS Total FROM product WHERE p_name='" + product + "'";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()) {
                    double total = rs.getDouble("Total");
                    dataset.setValue(product, total);
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }

        // Create Pie Chart
        JFreeChart pieChart = ChartFactory.createPieChart(
                "Customer Behavior Analysis", // Chart title
                dataset,
                true, // 
                true, // 
                false // 
        );

        // Display Pie Chart in a new frame
        ChartFrame chartFrame = new ChartFrame("Customer Behavior Pie Chart", pieChart);
        chartFrame.setSize(600, 500);
        chartFrame.setVisible(true);
    }//GEN-LAST:event_btn_bar_chartActionPerformed

    private void btn_line_chart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_line_chart1ActionPerformed
        // TODO add your handling code here:
        print_data();
    }//GEN-LAST:event_btn_line_chart1ActionPerformed

    private void btn_log_Out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_Out1ActionPerformed
        // TODO add your handling code here:
        Main_Application load_data = new Main_Application();
        // Show the next page
        load_data.setVisible(true);
        // Close the current page
        this.dispose();
    }//GEN-LAST:event_btn_log_Out1ActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(customer_behavior_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(customer_behavior_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(customer_behavior_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(customer_behavior_product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new customer_behavior_product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bar_chart;
    private javax.swing.JButton btn_line_chart1;
    private javax.swing.JButton btn_log_Out1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_product;
    // End of variables declaration//GEN-END:variables
}
