/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import code.product;
import code.readcsv;
import data.loadData;
import java.awt.print.PrinterException;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Praveen
 */
public class Product_Performance extends javax.swing.JFrame {

    /**
     * Creates new form Product_Performance
     */
    public Product_Performance() {
        initComponents();
        show_product_data();
    }
    private List<readcsv> loadedData;
    private void load_CSV() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            loadedData = loadData.loadcsv(selectedFile);
            display_product_data_table(loadedData);
//            ;
        }
    }
    private void display_product_data_table(List<readcsv> dataList) {
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dataList.size(); i++) {
            readcsv row = dataList.get(i);
            model.addRow(new Object[]{
                row.getTra_id(),
                row.getC_id(),
                row.getP_id(),
                row.getP_name(),
                row.getQuantity(),
                row.getP_unit(),
                row.getDate(),
                row.getPrice(),
                row.getRegion()
            });
        }
    }
    //retriew Code

    public ArrayList<product> ProductList() {
        ArrayList<product> ProductList = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {

                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ProductList;
    }

    public void show_product_data() {
        ArrayList<product> list = ProductList();
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        Object[] row = new Object[9];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTra_id();
            row[1] = list.get(i).getC_id();
            row[2] = list.get(i).getP_id();
            row[3] = list.get(i).getP_name();
            row[4] = list.get(i).getQuantity();
            row[5] = list.get(i).getP_unit();
            row[6] = list.get(i).getDate();
            row[7] = list.get(i).getPrice();
            row[8] = list.get(i).getRegion();

            model.addRow(row);
        }

    }

    private void print_data() {
        try {
            boolean complete = tbl_product.print(JTable.PrintMode.FIT_WIDTH,
                    new MessageFormat("Datas"),
                    new MessageFormat("Page {0}"));
            if (complete) {
                JOptionPane.showMessageDialog(null, "Complete");
            } else {
                JOptionPane.showMessageDialog(null, "Not Complete");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_search_bar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ibl_total_amount = new javax.swing.JLabel();
        btn_line_chart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        txt_serch_product = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_print = new javax.swing.JLabel();
        btn_line_chart1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_log_Out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Product Performance ");

        txt_search_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_barActionPerformed(evt);
            }
        });
        txt_search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_barKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Date");

        ibl_total_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ibl_total_amount.setText("0.00");

        btn_line_chart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_line_chart.setText("Line Chart");
        btn_line_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_line_chartActionPerformed(evt);
            }
        });

        tbl_product.setForeground(new java.awt.Color(204, 204, 204));
        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " TransactionID", "CustomerID", "ProductID", "ProductName", "Quantity	", "PriceperUnit", "Date", "TotalPrice", "Region"
            }
        ));
        jScrollPane1.setViewportView(tbl_product);

        txt_serch_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serch_productActionPerformed(evt);
            }
        });
        txt_serch_product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serch_productKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Product Name");

        btn_print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_printMouseClicked(evt);
            }
        });

        btn_line_chart1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_line_chart1.setText("Print");
        btn_line_chart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_line_chart1ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Sampath Food City (PVT) Ltd ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Total Price");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Search by");

        btn_log_Out.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_log_Out.setText("Home");
        btn_log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_OutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_log_Out)
                                .addGap(43, 43, 43)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_print, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(285, 285, 285))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_serch_product, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(38, 38, 38)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 354, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(60, 60, 60)
                                        .addComponent(ibl_total_amount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(btn_line_chart1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_line_chart))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(11, 11, 11)))
                        .addGap(36, 36, 36))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_log_Out, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jLabel3)
                            .addComponent(txt_serch_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txt_search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(ibl_total_amount))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_print)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_line_chart1)
                    .addComponent(btn_line_chart))
                .addGap(104, 104, 104))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_search_barKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_barKeyReleased
        // TODO add your handling code here:
        search_date();

    }//GEN-LAST:event_txt_search_barKeyReleased

    private void btn_line_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_line_chartActionPerformed
        // TODO add your handling code here:
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Add sample data (Product Name, Sales Value, Category)
        dataset.addValue(2376, "Sales", "Fish");
        dataset.addValue(2180, "Sales", "Beef");
        dataset.addValue(1976, "Sales", "Chicken");
        dataset.addValue(1340, "Sales", "Yogurt");
        dataset.addValue(1155, "Sales", "Cereal");
        dataset.addValue(995, "Sales", "Cheese");
        dataset.addValue(675, "Sales", "Bread");
        dataset.addValue(380, "Sales", "Banana");
        dataset.addValue(370, "Sales", "Milk");
        dataset.addValue(245, "Sales", "Apple");

        // Create the line chart
        JFreeChart chart = ChartFactory.createLineChart(
                "Product Performance Over Time", // Chart Title
                "Product Name", // X-l
                "Total Sales (LKR)", // Y
                dataset // Dataset
        );

        // Display chart in a new frame
        org.jfree.chart.ChartFrame frame = new org.jfree.chart.ChartFrame("Line Chart", chart);
        frame.setVisible(true);
        frame.setSize(600, 500);
    }//GEN-LAST:event_btn_line_chartActionPerformed

    private void txt_search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_barActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_barActionPerformed

    private void txt_serch_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serch_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serch_productActionPerformed

    private void txt_serch_productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serch_productKeyReleased
        // TODO add your handling code here:
        
       search_produt_name();
    }//GEN-LAST:event_txt_serch_productKeyReleased

    private void btn_printMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_printMouseClicked
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btn_printMouseClicked

    private void btn_line_chart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_line_chart1ActionPerformed
        // TODO add your handling code here:
            print_data();
    }//GEN-LAST:event_btn_line_chart1ActionPerformed

    private void btn_log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_OutActionPerformed
        // TODO add your handling code here:

        Main_Application load_data = new Main_Application();
        // Show the next page
        load_data.setVisible(true);
        // Close the current page
        this.dispose();
    }//GEN-LAST:event_btn_log_OutActionPerformed
    public void sum_of_total() {
        double total = 0;
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        for (int i = 0; i < tbl_product.getRowCount(); i++) {
            total = total + Double.parseDouble(model.getValueAt(i, 7).toString());

        }
        ibl_total_amount.setText(Double.toString(total));
    }
public void search_produt_name(){
    ArrayList<product> ProductList = new ArrayList<>();
        String search = txt_serch_product.getText().trim();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product where p_name like '%" + search + "%'";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {
                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);

            }

            DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
            model.setRowCount(0);

            Object[] row = new Object[9];

            for (int i = 0; i < ProductList.size(); i++) {
                row[0] = ProductList.get(i).getTra_id();
                row[1] = ProductList.get(i).getC_id();
                row[2] = ProductList.get(i).getP_id();
                row[3] = ProductList.get(i).getP_name();
                row[4] = ProductList.get(i).getQuantity();
                row[5] = ProductList.get(i).getP_unit();
                row[6] = ProductList.get(i).getDate();
                row[7] = ProductList.get(i).getPrice();
                row[8] = ProductList.get(i).getRegion();

                model.addRow(row);
            }
            sum_of_total();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}

private void search_date(){
ArrayList<product> ProductList = new ArrayList<>();
        String search = txt_search_bar.getText().trim();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product where Date like '%" + search + "%'";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {
                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);

            }

            DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
            model.setRowCount(0);

            Object[] row = new Object[9];

            for (int i = 0; i < ProductList.size(); i++) {
                row[0] = ProductList.get(i).getTra_id();
                row[1] = ProductList.get(i).getC_id();
                row[2] = ProductList.get(i).getP_id();
                row[3] = ProductList.get(i).getP_name();
                row[4] = ProductList.get(i).getQuantity();
                row[5] = ProductList.get(i).getP_unit();
                row[6] = ProductList.get(i).getDate();
                row[7] = ProductList.get(i).getPrice();
                row[8] = ProductList.get(i).getRegion();

                model.addRow(row);
            }
            sum_of_total();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Product_Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Product_Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Product_Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Product_Performance.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Product_Performance().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_line_chart;
    private javax.swing.JButton btn_line_chart1;
    private javax.swing.JButton btn_log_Out;
    private javax.swing.JLabel btn_print;
    private javax.swing.JLabel ibl_total_amount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_search_bar;
    private javax.swing.JTextField txt_serch_product;
    // End of variables declaration//GEN-END:variables
}
