/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import code.product;
import code.readcsv;
import data.loadData;
import database.db;
import java.awt.print.PrinterException;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Praveen
 */
public class product_data_load extends javax.swing.JFrame {

  
    public product_data_load() {
        initComponents();
        show_product_data();
    }
    private List<readcsv> loadedData;

    private void load_CSV() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            loadedData = loadData.loadcsv(selectedFile);
            display_product_data_table(loadedData);
//            ;
        }
    }

    private void display_product_data_table(List<readcsv> dataList) {
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dataList.size(); i++) {
            readcsv row = dataList.get(i);
            model.addRow(new Object[]{
                row.getTra_id(),
                row.getC_id(),
                row.getP_id(),
                row.getP_name(),
                row.getQuantity(),
                row.getP_unit(),
                row.getDate(),
                row.getPrice(),
                row.getRegion()

            });
        }
    }
    //retriew Code

    public ArrayList<product> ProductList() {
        ArrayList<product> ProductList = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {

                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ProductList;
    }

    public void show_product_data() {
        ArrayList<product> list = ProductList();
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        Object[] row = new Object[9];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTra_id();
            row[1] = list.get(i).getC_id();
            row[2] = list.get(i).getP_id();
            row[3] = list.get(i).getP_name();
            row[4] = list.get(i).getQuantity();
            row[5] = list.get(i).getP_unit();
            row[6] = list.get(i).getDate();
            row[7] = list.get(i).getPrice();
            row[8] = list.get(i).getRegion();

            model.addRow(row);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btn_print = new javax.swing.JButton();
        btn_save1 = new javax.swing.JButton();
        btn_log_Out1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " TransactionID", "CustomerID", "ProductID", "ProductName", "Quantity	", "PriceperUnit", "Date", "TotalPrice", "Region"
            }
        ));
        jScrollPane1.setViewportView(tbl_product);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Load Data");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Sampath Food City (PVT) Ltd ");

        btn_print.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_print.setText("Print");
        btn_print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_printActionPerformed(evt);
            }
        });

        btn_save1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_save1.setText("Save");
        btn_save1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save1ActionPerformed(evt);
            }
        });

        btn_log_Out1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_log_Out1.setText("Home");
        btn_log_Out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_Out1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_save1)
                        .addGap(18, 18, 18)
                        .addComponent(btn_print))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_log_Out1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btn_log_Out1)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_print)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_save1)
                        .addComponent(jButton1)))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        load_CSV();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_printActionPerformed
        // TODO add your handling code here:
        try {
            boolean complete = tbl_product.print(JTable.PrintMode.FIT_WIDTH,
                    new MessageFormat("Datas"),
                    new MessageFormat("Page {0}"));
            if (complete) {
                JOptionPane.showMessageDialog(null, "Complete");
            } else {
                JOptionPane.showMessageDialog(null, "Not Complete");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        
    }//GEN-LAST:event_btn_printActionPerformed

    private void btn_save1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save1ActionPerformed
        // TODO add your handling code here:
        save_data();
    }//GEN-LAST:event_btn_save1ActionPerformed

    private void btn_log_Out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_Out1ActionPerformed
        // TODO add your handling code here:
        
        Main_Application load_data = new Main_Application();
        // Show the next page
        load_data.setVisible(true);
        // Close the current page
        this.dispose();
    }//GEN-LAST:event_btn_log_Out1ActionPerformed
 
    
    private void displayDataTable(List<readcsv> dataList){
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dataList.size(); i++){
            readcsv row = dataList.get(i);
            model.addRow(new Object[]{
            row.getTra_id(),
            row.getC_id(),
            row.getP_id(),
            row.getP_name(),
            row.getQuantity(),
            row.getP_unit(),
            row.getDate(),
            row.getPrice(),
            row.getRegion()
            
        });
        }
    }
    
    public void save_data() {

        try {
            Connection con;
            PreparedStatement pst;
            String query = "INSERT INTO product (tra_id, c_id, p_id, p_name, quantity, p_unit, date, price, region) VALUES(?,?,?,?,?,?,?,?,?)";
            con = db.getConnection();
            pst = con.prepareStatement(query);
            DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();

            double total = 0;
            for (int i = 0; i < model.getRowCount(); i++) {
                int tra_id = Integer.parseInt(model.getValueAt(i, 0).toString());
                int c_id = Integer.parseInt(model.getValueAt(1, 1).toString());
                int p_id = Integer.parseInt(model.getValueAt(i, 2).toString());
                String p_name = model.getValueAt(i, 3).toString();
                int quantity = Integer.parseInt(model.getValueAt(i, 4).toString());
                double p_unit = Double.parseDouble(model.getValueAt(i, 5).toString());
                String date = model.getValueAt(1, 6).toString();
                double price = Double.parseDouble(model.getValueAt(i, 7).toString());
                String region = model.getValueAt(i, 8).toString();

                total = total + price;
                pst.setInt(1, tra_id);
                pst.setInt(2, c_id);
                pst.setInt(3, p_id);
                pst.setString(4, p_name);
                pst.setInt(5, quantity);
                pst.setDouble(6, p_unit);
                pst.setString(7, date);
                pst.setDouble(8, price);
                pst.setString(9, region);
                pst.addBatch();
                pst.executeUpdate();
            }
            JOptionPane.showMessageDialog(null, "Data saved successfully!");
        } catch (SQLException e) {
            e.printStackTrace();
            System.out.println("Error saving data to the database: " + e.getMessage());

        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product_data_load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product_data_load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product_data_load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product_data_load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product_data_load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_log_Out1;
    private javax.swing.JButton btn_print;
    private javax.swing.JButton btn_save1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_product;
    // End of variables declaration//GEN-END:variables
}
