/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import code.product;
import code.readcsv;
import data.loadData;
import java.awt.print.PrinterException;
import java.io.File;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;


/**
 *
 * @author Praveen
 */
public class Regional_Sales_Analysis extends javax.swing.JFrame {

    /**
     * Creates new form Regional_Sales_Analysis
     */
    public Regional_Sales_Analysis() {
        initComponents();
        show_product_data();
        
    }
    
    private List<readcsv> loadedData;

    private void load_CSV() {
        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            loadedData = loadData.loadcsv(selectedFile);
            display_product_data_table(loadedData);
//            ;
        }
    }

    private void display_product_data_table(List<readcsv> dataList) {
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        model.setRowCount(0);
        for (int i = 0; i < dataList.size(); i++) {
            readcsv row = dataList.get(i);
            model.addRow(new Object[]{
                row.getTra_id(),
                row.getC_id(),
                row.getP_id(),
                row.getP_name(),
                row.getQuantity(),
                row.getP_unit(),
                row.getDate(),
                row.getPrice(),
                row.getRegion()

            });
        }
    }
    //retriew Code

    public ArrayList<product> ProductList() {
        ArrayList<product> ProductList = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {

                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return ProductList;
    }

    public void show_product_data() {
        ArrayList<product> list = ProductList();
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        Object[] row = new Object[9];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getTra_id();
            row[1] = list.get(i).getC_id();
            row[2] = list.get(i).getP_id();
            row[3] = list.get(i).getP_name();
            row[4] = list.get(i).getQuantity();
            row[5] = list.get(i).getP_unit();
            row[6] = list.get(i).getDate();
            row[7] = list.get(i).getPrice();
            row[8] = list.get(i).getRegion();

            model.addRow(row);
        }

    }

    private void print_data() {
        try {
            boolean complete = tbl_product.print(JTable.PrintMode.FIT_WIDTH,
                    new MessageFormat("Datas"),
                    new MessageFormat("Page {0}"));
            if (complete) {
                JOptionPane.showMessageDialog(null, "Complete");
            } else {
                JOptionPane.showMessageDialog(null, "Not Complete");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_product = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_serch_product = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_search_bar = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ibl_total_amount = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btn_line_chart1 = new javax.swing.JButton();
        btn_bar_chart = new javax.swing.JButton();
        btn_pie_chart = new javax.swing.JButton();
        btn_log_Out = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));

        tbl_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " TransactionID", "CustomerID", "ProductID", "ProductName", "Quantity	", "PriceperUnit", "Date", "TotalPrice", "Region"
            }
        ));
        jScrollPane1.setViewportView(tbl_product);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Regional Sales Analysis");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Sampath Food City (PVT) Ltd ");

        txt_serch_product.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_serch_productActionPerformed(evt);
            }
        });
        txt_serch_product.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_serch_productKeyReleased(evt);
            }
        });

        jLabel3.setText("Product Name");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Date");

        txt_search_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_search_barActionPerformed(evt);
            }
        });
        txt_search_bar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_search_barKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 0, 51));
        jLabel6.setText("Total Price");

        ibl_total_amount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ibl_total_amount.setText("0.00");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("Search by");

        btn_line_chart1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_line_chart1.setText("Print");
        btn_line_chart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_line_chart1ActionPerformed(evt);
            }
        });

        btn_bar_chart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_bar_chart.setText("Bar Chart");
        btn_bar_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bar_chartActionPerformed(evt);
            }
        });

        btn_pie_chart.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_pie_chart.setText("Pie Chart");
        btn_pie_chart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pie_chartActionPerformed(evt);
            }
        });

        btn_log_Out.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_log_Out.setText("Home");
        btn_log_Out.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_OutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btn_line_chart1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_bar_chart)
                        .addGap(18, 18, 18)
                        .addComponent(btn_pie_chart))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btn_log_Out, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel5))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(68, 68, 68)
                                        .addComponent(jLabel3)
                                        .addGap(28, 28, 28)
                                        .addComponent(txt_serch_product, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(175, 175, 175)
                                        .addComponent(jLabel2)
                                        .addGap(30, 30, 30)
                                        .addComponent(txt_search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(ibl_total_amount)))
                                .addGap(12, 12, 12)))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(111, 111, 111)
                    .addComponent(jLabel1)
                    .addContainerGap(891, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_log_Out)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(txt_serch_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txt_search_bar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(ibl_total_amount))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_line_chart1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_pie_chart)
                        .addComponent(btn_bar_chart)))
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(184, 184, 184)
                    .addComponent(jLabel1)
                    .addContainerGap(392, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_serch_productActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_serch_productActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_serch_productActionPerformed

    private void txt_serch_productKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_serch_productKeyReleased
        // TODO add your handling code here:

        search_produt_name();
    }//GEN-LAST:event_txt_serch_productKeyReleased

    private void txt_search_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_search_barActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_search_barActionPerformed

    private void txt_search_barKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_search_barKeyReleased
        // TODO add your handling code here:
        search_date();
    }//GEN-LAST:event_txt_search_barKeyReleased

    private void btn_line_chart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_line_chart1ActionPerformed
        // TODO add your handling code here:
        print_data();
    }//GEN-LAST:event_btn_line_chart1ActionPerformed

    private void btn_bar_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bar_chartActionPerformed
        // TODO add your handling code here:
        bar_chart();
    }//GEN-LAST:event_btn_bar_chartActionPerformed

    private void btn_pie_chartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pie_chartActionPerformed
        // TODO add your handling code here:
        pie_chart();
    }//GEN-LAST:event_btn_pie_chartActionPerformed

    private void btn_log_OutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_OutActionPerformed
        // TODO add your handling code here:

        Main_Application load_data = new Main_Application();
        // Show the next page
        load_data.setVisible(true);
        // Close the current page
        this.dispose();
    }//GEN-LAST:event_btn_log_OutActionPerformed

    //pie chart data analising for regional
    private void pie_chart(){
    DefaultPieDataset pieDataset = new DefaultPieDataset();

        try {
            Connection con = database.db.getConnection();
            Statement st = con.createStatement();
            
            String[] regions = { "Matara", "Colombo", "Kalutara","Galle"};

            for (String region : regions) {
                String query = "SELECT SUM(price) AS Total FROM product WHERE region='" + region + "'";
                ResultSet rs = st.executeQuery(query);
                if (rs.next()) {
                    double total = rs.getDouble("Total");
                    pieDataset.setValue(region, total);
                }
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

// Create Pie Chart
        JFreeChart pieChart = ChartFactory.createPieChart(
                "Regional Sales Performance",
                pieDataset,
                true, 
                true, 
                false 
        );

// Display the chart 
        ChartFrame pieFrame = new ChartFrame("Regional Sales Performance", pieChart);
        pieFrame.setSize(600, 650);
        pieFrame.setVisible(true);
    }
    
    //bar chart
    private void bar_chart(){
     DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try {
            Connection con = database.db.getConnection();
            Statement st = con.createStatement();

            // List of regions
            String[] regions = { "Matara", "Colombo", "Kalutara","Galle"};

            for (String region : regions) {
          
                String query = "SELECT COALESCE(SUM(price), 0) AS Total FROM product WHERE region='" + region + "'";
                ResultSet rs = st.executeQuery(query);
                double total = 0;
                if (rs.next()) {
                    total = rs.getDouble("Total");
                }
                dataset.addValue(total, "product", region); 
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        // Create Bar Chart
        JFreeChart chart = ChartFactory.createBarChart(
                "Regional Sales Performance", // Chart title
                "Region", //x
                "Total Sales (LKR)", //y
                dataset
        );

        // Optional: customize chart appearance
        CategoryPlot plot = chart.getCategoryPlot();
        plot.setRangeGridlinePaint(java.awt.Color.BLACK);

        // Display the chart
        ChartFrame frame = new ChartFrame("Regional Sales Bar Chart", chart);
        frame.setSize(700, 500);
        frame.setVisible(true);
    }
    
    
    //total of product price
    public void sum_of_total() {
        double total = 0;
        DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
        for (int i = 0; i < tbl_product.getRowCount(); i++) {
            total = total + Double.parseDouble(model.getValueAt(i, 7).toString());

        }
        ibl_total_amount.setText(Double.toString(total));
    }
public void search_produt_name(){
    ArrayList<product> ProductList = new ArrayList<>();
        String search = txt_serch_product.getText().trim();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product where p_name like '%" + search + "%'";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {
                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);

            }

            DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
            model.setRowCount(0);

            Object[] row = new Object[9];

            for (int i = 0; i < ProductList.size(); i++) {
                row[0] = ProductList.get(i).getTra_id();
                row[1] = ProductList.get(i).getC_id();
                row[2] = ProductList.get(i).getP_id();
                row[3] = ProductList.get(i).getP_name();
                row[4] = ProductList.get(i).getQuantity();
                row[5] = ProductList.get(i).getP_unit();
                row[6] = ProductList.get(i).getDate();
                row[7] = ProductList.get(i).getPrice();
                row[8] = ProductList.get(i).getRegion();

                model.addRow(row);
            }
            sum_of_total();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}

private void search_date(){
ArrayList<product> ProductList = new ArrayList<>();
        String search = txt_search_bar.getText().trim();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from product where Date like '%" + search + "%'";
            ResultSet rs = st.executeQuery(query);
            product pro;
            while (rs.next()) {
                pro = new product(rs.getInt("tra_id"), rs.getInt("c_id"), rs.getInt("p_id"), rs.getString("p_name"), rs.getDouble("quantity"), rs.getDouble("p_unit"), rs.getString("date"), rs.getDouble("price"), rs.getString("region"));
                ProductList.add(pro);

            }

            DefaultTableModel model = (DefaultTableModel) tbl_product.getModel();
            model.setRowCount(0);

            Object[] row = new Object[9];

            for (int i = 0; i < ProductList.size(); i++) {
                row[0] = ProductList.get(i).getTra_id();
                row[1] = ProductList.get(i).getC_id();
                row[2] = ProductList.get(i).getP_id();
                row[3] = ProductList.get(i).getP_name();
                row[4] = ProductList.get(i).getQuantity();
                row[5] = ProductList.get(i).getP_unit();
                row[6] = ProductList.get(i).getDate();
                row[7] = ProductList.get(i).getPrice();
                row[8] = ProductList.get(i).getRegion();

                model.addRow(row);
            }
            sum_of_total();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Regional_Sales_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Regional_Sales_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Regional_Sales_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Regional_Sales_Analysis.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Regional_Sales_Analysis().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bar_chart;
    private javax.swing.JButton btn_line_chart1;
    private javax.swing.JButton btn_log_Out;
    private javax.swing.JButton btn_pie_chart;
    private javax.swing.JLabel ibl_total_amount;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_product;
    private javax.swing.JTextField txt_search_bar;
    private javax.swing.JTextField txt_serch_product;
    // End of variables declaration//GEN-END:variables
}
