/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;


import code.user;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Praveen
 */
public class User_Management extends javax.swing.JFrame {

    /**
     * Creates new form User_Management
     */
    public User_Management() {
        initComponents();
        show_user_data();
    }
    //retriew Code

    public ArrayList<user> user_list() {
        ArrayList<user> user_list = new ArrayList<>();
        try {
            Connection con;
            Statement st;
            con = database.db.getConnection();
            st = con.createStatement();
            String query = "Select * from user";
            ResultSet rs = st.executeQuery(query);
            user users;
            while (rs.next()) {

                users = new user(rs.getInt("user_id"), rs.getString("user_name"), rs.getString("password"), rs.getString("role"));
                user_list.add(users);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return user_list;
    }

    public void show_user_data() {
        ArrayList<user> list =user_list();
        DefaultTableModel model = (DefaultTableModel) tbl_user.getModel();
        Object[] row = new Object[4];

        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getUser_id();
            row[1] = list.get(i).getUser_name();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getRole();
          
            model.addRow(row);
        }

    }

    private void print_data() {
        try {
            boolean complete = tbl_user.print(JTable.PrintMode.FIT_WIDTH,
                    new MessageFormat("Datas"),
                    new MessageFormat("Page {0}"));
            if (complete) {
                JOptionPane.showMessageDialog(null, "Complete");
            } else {
                JOptionPane.showMessageDialog(null, "Not Complete");
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_user = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_user_id = new javax.swing.JTextField();
        txt_password = new javax.swing.JTextField();
        txt_user_name2 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btn_add_user = new javax.swing.JButton();
        btn_edit_user = new javax.swing.JButton();
        btn_ptint = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        btn_log_Out1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        tbl_user.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "user_id", "user_name", "password", "role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_userMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_user);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Sampath Food City (PVT) Ltd ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("User Management");

        txt_user_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_user_idActionPerformed(evt);
            }
        });

        txt_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passwordActionPerformed(evt);
            }
        });

        txt_user_name2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_user_name2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "admin", "user" }));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 0, 51));
        jLabel7.setText("User ID");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 0, 51));
        jLabel8.setText("User name");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 0, 51));
        jLabel9.setText("Password");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 0, 51));
        jLabel10.setText("Role");

        btn_add_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_add_user.setText("Add User");
        btn_add_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_userActionPerformed(evt);
            }
        });

        btn_edit_user.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_edit_user.setText("Edit");
        btn_edit_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_edit_userActionPerformed(evt);
            }
        });

        btn_ptint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ptint.setText("Print");
        btn_ptint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ptintActionPerformed(evt);
            }
        });

        btn_delete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        btn_log_Out1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_log_Out1.setText("Home");
        btn_log_Out1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_log_Out1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(553, 553, 553)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_log_Out1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_add_user)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_edit_user))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_ptint))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(17, 17, 17)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txt_user_name2)
                                        .addComponent(txt_user_id)
                                        .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(94, 94, 94))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))))
                .addGap(43, 43, 43)
                .addComponent(btn_log_Out1)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_user_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_user_name2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_add_user)
                            .addComponent(btn_edit_user))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_delete)
                            .addComponent(btn_ptint))))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_user_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_user_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_user_idActionPerformed

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_user_name2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_user_name2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_user_name2ActionPerformed

    private void btn_add_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_userActionPerformed
        // TODO add your handling code here:
add_user();
    }//GEN-LAST:event_btn_add_userActionPerformed

    private void btn_edit_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_edit_userActionPerformed
        // TODO add your handling code here:
        edit_user();
    }//GEN-LAST:event_btn_edit_userActionPerformed

    private void btn_ptintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ptintActionPerformed
        // TODO add your handling code here:
        print_data();
    }//GEN-LAST:event_btn_ptintActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
        delete_user();
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_userMouseClicked
        // TODO add your handling code here:
        int i = tbl_user.getSelectedRow();
        TableModel model = tbl_user.getModel();
        txt_user_id.setText(model.getValueAt(i, 0).toString());
        txt_user_name2.setText(model.getValueAt(i, 1).toString());
        txt_password.setText(model.getValueAt(i, 2).toString());
        jComboBox1.setSelectedItem(model.getValueAt(i, 3).toString());
    }//GEN-LAST:event_tbl_userMouseClicked

    private void btn_log_Out1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_log_Out1ActionPerformed
    Main_Application load_data = new Main_Application();
        // Show the next page
        load_data.setVisible(true);
        // Close the current page
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btn_log_Out1ActionPerformed
private void edit_user(){

try {
            Connection con;
            PreparedStatement pst;
            con = database.db.getConnection();
            String username = txt_user_name2.getText();
            String password = txt_password.getText();
            String role = jComboBox1.getSelectedItem().toString();

            String query = "update user set password = '" + password + "', role = '" + role + "' where user_name = '" + username + "' ";
            pst = con.prepareStatement(query);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "succesfully Edited");
            
             DefaultTableModel model = (DefaultTableModel) tbl_user.getModel();
            model.setRowCount(0);
            show_user_data();

            
            txt_password.setText("");
            txt_user_id.setText("");
            txt_user_name2.setText("");
            jComboBox1.setSelectedIndex(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }}
private void add_user(){
    try {
            Connection con;
            PreparedStatement pst;
            con = database.db.getConnection();
            String user_id = txt_user_id.getText();
            String username = txt_user_name2.getText();
            String password = txt_password.getText();
            String role = jComboBox1.getSelectedItem().toString();

            // Validation
            if (username.isEmpty() ||user_id.isEmpty() || password.isEmpty() || role.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Please fill all text box");
                return;
            }

            // Insert new user into database
            String query = "INSERT INTO user (user_id,user_name, password, role) VALUES (?,?, ?, ?)";
            pst = con.prepareStatement(query);
            pst.setString(1, user_id);
            pst.setString(2, username);
            pst.setString(3, password);
            pst.setString(4, role);

            int row = pst.executeUpdate();

            if (row > 0) {
                JOptionPane.showMessageDialog(null, "User Added Successfully!");

                // Refresh table after insert
                DefaultTableModel model = (DefaultTableModel) tbl_user.getModel();
                model.setRowCount(0);
                show_user_data();

                // Clear text fields
            txt_password.setText("");
            txt_user_id.setText("");
            txt_user_name2.setText("");
            jComboBox1.setSelectedIndex(0);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}

private void delete_user(){
            // TODO add your handling code here:
        try {
            Connection con;
            PreparedStatement pst;
            con = database.db.getConnection();
            String user_id = txt_user_id.getText();
            String username = txt_user_name2.getText();
            String password = txt_password.getText();
            String role = jComboBox1.getSelectedItem().toString();

            String query = "delete from user where user_name = '"+username+"'";
            pst = con.prepareStatement(query);
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfuly Deleted");
            
             DefaultTableModel model = (DefaultTableModel) tbl_user.getModel();
            model.setRowCount(0);
            show_user_data();

            
            txt_password.setText("");
            txt_user_id.setText("");
            txt_user_name2.setText("");
            jComboBox1.setSelectedIndex(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User_Management.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User_Management().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_user;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit_user;
    private javax.swing.JButton btn_log_Out1;
    private javax.swing.JButton btn_ptint;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_user;
    private javax.swing.JTextField txt_password;
    private javax.swing.JTextField txt_user_id;
    private javax.swing.JTextField txt_user_name2;
    // End of variables declaration//GEN-END:variables
}
